services:
  backend:
    build:
      context: ./back/auth_service
    environment:
      - PORT=8020
    env_file:
      - ./back/auth_service/.env
    ports:
      - "8001:8020"
    volumes:
       - ./back/auth_service:/app
    command: >
      sh -c 'chmod +x /app/migrate.sh && sh /app/migrate.sh && sh /app/entrypoint.sh'
    depends_on:
      - database

  frontend:
    build:
      context: ./front
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  database:
    image: postgres:13-alpine
    restart: always
    command: -p 5432
    env_file:
      - ./back/auth_service/.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data:
