# Generated by Django 4.2.19 on 2025-02-28 12:56

import uuid
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_reset_token_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
