# Generated by Django 4.2.19 on 2025-02-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
