# Generated by Django 4.2.19 on 2025-02-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_verification_token_expiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="token_expiry",
        ),
    ]
