# Generated by Django 4.2.19 on 2025-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_user_token_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="administrative_area_level_1",
            field=models.CharField(
                blank=True, help_text="Region / State", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="administrative_area_level_2",
            field=models.CharField(
                blank=True, help_text="Department / District", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True, help_text="Postal code", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="types",
            field=models.CharField(
                blank=True,
                help_text="Google address types (e.g., street_address, route)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non-binary", "Non-binary"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
