# Generated by Django 4.2.19 on 2025-08-01 00:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_address_administrative_area_level_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_carousel', models.BooleanField(default=False)),
                ('profile_url', models.CharField(max_length=255)),
                ('certified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('level', models.CharField(default='PRO', max_length=50)),
                ('subscribers_vb', models.PositiveIntegerField(default=0)),
                ('subscribers_instagram', models.PositiveIntegerField(default=0)),
                ('subscribers_youtube', models.PositiveIntegerField(default=0)),
                ('image1', models.CharField(blank=True, max_length=255, null=True)),
                ('image2', models.CharField(blank=True, max_length=255, null=True)),
                ('image3', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
