# Generated by Django 4.2.19 on 2025-09-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_athlete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="athlete",
            name="subscribers_vb",
        ),
        migrations.AddField(
            model_name="athlete",
            name="subscribers_facebook",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="bio",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
