# Generated by Django 4.2.19 on 2025-09-15 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_conversation_mediaasset_sportcategory_companyprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="athlete_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
