# Generated by Django 4.2.19 on 2025-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_athlete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
