# Generated by Django 4.2.19 on 2025-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_user_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
