# Generated by Django 4.2.19 on 2025-09-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_athlete_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
