name: Python CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r ./back/auth_service/requirements.txt

    - name: Flake8 linting
      run: |
        python3 -m flake8 ./back --max-line-length=120 --exclude=venv,__pycache__,migrations
      
    - name: Test coverage (pytest 8.3.4)
      run: |
        pytest ./back --cov=./back/auth_service/core --cov-report=term --cov-fail-under=0

    - name: Linter (pylint 3.3.4)
      run: |
        pylint --rcfile=./back/auth_service/.pylintrc ./back/auth_service
