name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r ./back/auth_service/requirements.txt

    - name: Flake8 linting
      run: |
        python3 -m flake8 ./back --max-line-length=88 --exclude=venv,__pycache__

    - name: Test run
      run: |
        pytest ./back
      
    - name: Test coverage
      run: |
        pytest ./back --cov=./back/auth_service/core --cov-report=term --cov-fail-under=90
      

    - name: Pylint linting
      run: |
        pylint --rcfile=./back/.pylintrc ./back/auth_service/core
        pylint --rcfile=./back/.pylintrc ./back/auth_service/api
